services:
  client:
    restart: always
    image: bitzer-me-client
    ports:
      - "3000:3000"
    networks:
      - bitzer-me
  server:
    restart: always
    image: bitzer-me-server
    ports:
      - "5000:5000"
    networks:
      - bitzer-me
# define local network for this app
networks:
  bitzer-me:
    driver: bridge